---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 5f9666fba917780ce0b1a516a2192063b5e59ce9
    fabric8.io/git-branch: master
    fabric8.io/git-url: https://github.com/sibyg/java-security-samples.git
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/java-security-samples
    fabric8.io/scm-tag: HEAD
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    app: java-security-samples
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: org.example
  name: java-security-samples
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: java-security-samples
    provider: fabric8
    group: org.example
  type: LoadBalancer
